Separate stderr from stdout
jonaslu/ain pull request #20
Opened 2023-11-15 07:52 UTC by erikeah

This PR solves #17 .

Excuse me by late PR, I hope you are still interested in this feature.

2023-11-20 14:08 UTC, jonaslu commented
Sure and thanks, it still makes sense. I'll have a look in the coming days.

2023-11-25 11:38 UTC, jonaslu commented on internal/pkg/call/call.go
> +			return Output{StdOut: []byte(command)}, nil
Change getAsString() into returning a []byte array with a matching method name, it's currently converting a string to a []byte and then into a string again

2023-11-25 11:38 UTC, jonaslu commented on internal/pkg/call/call.go
> +type Output struct {
Output is too generic, I'd call it BackendOutput

2023-11-25 11:40 UTC, jonaslu requested changes
Test plan: None is only ok if it's a textual (non functional change such as pure refactor or changes in say a README.md file). Also please keep the test-plan formatting. It'll be easier on the eyes. I'll submit a .gitmessage template.

Any functional change needs tests that others can run and reproduce.
It helps to think in terms of code-coverage: make sure you've covered all branches of the code you've changed (especially cases where errors are returned).

2024-01-08 10:10 UTC, erikeah commented
I will give a try once I've free time, thanks for feedback, makes sense!

2024-03-30 20:52 UTC, jonaslu commented
This has been fixed in eb9fa6c, closing this

2024-03-30 20:52 UTC, closed without merging